import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { buildGraph, buildThread, isSessionId } from './graph.js';
import { createSession, sendText, isManagedName, sessionExists } from './tmux.js';

const HANDOFF_DIR = join(homedir(), '.claude', 'cc-deck', 'handoffs');
// claude lives alongside node (nvm bin); make sure a minimal systemd PATH finds it.
const PATH = `${dirname(process.execPath)}:${process.env.PATH || ''}`;

function err(status, message) { const e = new Error(message); e.statusCode = status; return e; }

function threadToMarkdown(title, messages) {
  let md = `# Context handoff: ${title}\n\n_Full transcript excerpt, generated by cc-deck from a related Claude session._\n\n`;
  for (const m of messages) {
    md += `## ${m.role === 'user' ? 'User' : 'Claude'}${m.ts ? ` · ${m.ts}` : ''}\n\n${m.text || '(no text)'}\n\n`;
    if (m.tools && m.tools.length) md += `_(tools used: ${m.tools.join(', ')})_\n\n`;
  }
  return md;
}

// Summarize a transcript into a concise handoff via headless `claude -p`.
export function summarize(text) {
  return new Promise((resolve, reject) => {
    const prompt =
      'You are writing a CONTEXT HANDOFF so a new Claude Code session can pick up this work with full understanding. ' +
      'From the session transcript below, produce a concise, concrete briefing with these sections: ' +
      'Goal, Key decisions & rationale, Current state, Important files / paths / commands, Open threads / next steps. ' +
      'Use tight bullet points. No pleasantries, no preamble.\n\n=== SESSION TRANSCRIPT ===\n' + text;
    let out = '', errOut = '';
    let child;
    try { child = spawn('claude', ['-p', '--model', 'sonnet'], { env: { ...process.env, PATH } }); }
    catch (e) { return reject(err(500, 'could not launch claude: ' + e.message)); }
    const timer = setTimeout(() => { try { child.kill('SIGKILL'); } catch { /* */ } reject(err(504, 'summary timed out')); }, 120_000);
    child.stdout.on('data', (d) => { out += d; });
    child.stderr.on('data', (d) => { errOut += d; });
    child.on('error', (e) => { clearTimeout(timer); reject(err(500, 'claude error: ' + e.message)); });
    child.on('close', (code) => {
      clearTimeout(timer);
      if (code === 0 && out.trim()) resolve(out.trim());
      else reject(err(500, 'summary failed: ' + (errOut.trim() || `exit ${code}`)));
    });
    child.stdin.end(prompt);
  });
}

// Build the handoff file. scope: 'summary' | 'thread'. uuid optional (defaults to
// the session head = whole conversation); pass a node uuid for "up to this point".
async function buildHandoffFile({ sourceId, cwd, uuid, scope, title }) {
  if (!isSessionId(sourceId)) throw err(400, 'invalid source session id');
  let u = uuid;
  if (!u) {
    const g = await buildGraph(sourceId, cwd);
    const cur = g.nodes.find((n) => n.current) || g.nodes[g.nodes.length - 1];
    u = cur && cur.id;
    if (!title) title = g.title;
  }
  if (!u) throw err(400, 'no conversation content to share');
  const { messages } = await buildThread(sourceId, u, cwd);
  if (!messages.length) throw err(400, 'no messages to share');

  let content;
  if (scope === 'summary') {
    const text = messages.map((m) => `${m.role === 'user' ? 'User' : 'Claude'}: ${m.text}`).join('\n\n').slice(0, 120_000);
    const summary = await summarize(text);
    content = `# Context handoff (AI summary): ${title || 'session'}\n\n_Generated by cc-deck from a related Claude session (${messages.length} messages)._\n\n${summary}\n`;
  } else {
    content = threadToMarkdown(title || 'session', messages);
  }

  await mkdir(HANDOFF_DIR, { recursive: true });
  const slug = (title || 'session').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'session';
  const file = join(HANDOFF_DIR, `${slug}-${Date.now().toString(36)}.md`);
  await writeFile(file, content);
  return { file, messages: messages.length, scope };
}

// Single-line instruction Claude will act on (newlines would submit early).
function seedNote(file) {
  return `I'm continuing work with context from a related session. Read this handoff file and use it to ground your work: ${file} — then confirm the goal and current state in one line.`;
}

// Build the handoff and deliver it to a destination.
//  dest: 'new'      -> launch a new session (in targetDir, default source cwd) seeded with the context
//        'running'  -> inject into an existing cc-deck session (targetSession)
export async function runHandoff(opts) {
  const built = await buildHandoffFile(opts);
  const note = seedNote(built.file);

  if (opts.dest === 'running') {
    const target = opts.targetSession;
    if (!isManagedName(target) || !(await sessionExists(target))) throw err(400, 'target session not found');
    await sendText(target, note);
    return { ...built, dest: 'running', name: target };
  }
  // default: new session
  const dir = opts.targetDir || opts.cwd;
  if (!dir) throw err(400, 'no target directory for the new session');
  const name = await createSession({ dir, title: opts.title ? `${opts.title} (ctx)` : undefined, seed: note });
  return { ...built, dest: 'new', name };
}
